name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello > sample.log

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: sample.log
    
  stage-2:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
    - name: Download log
      uses: actions/download-artifact@v3
      with:
        name : my-artifact
    - name: List all the files
      run : ls -R
    - name: Display content
      run: cat sample.log
    
#     - name: Send mail
#       uses: dawidd6/action-send-mail@v3
#       with:
#         server_address: smtp.gmail.com
#         server_port: 465

#         username: ${{ secrets.MAIL_USERNAME }}
#         password: ${{ secrets.MAIL_PASSWORD }}

#         subject: Github Actions job result
#         to: ankitvelani@gmail.com

#         from: Ankit.Velani@gmail.com

#         body: Build job of ${{ github.repository }} completed successfully!
