name: learn-github-actions

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

run-name: ${{ github.actor }} is learning GitHub Actions
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello, writting output into log file" > sample.log

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: sample.log
    
  stage-2:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
          python-version: 3.x
    - uses: actions/download-artifact@v3
      with:
        name : my-artifact
    - name: Read log file using Python
      run: python read_data.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./*
  
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465

        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}

        subject: Github Actions job result
        to: ankitvelani@gmail.com

        from: Ankit.Velani@gmail.com

        body: Build job of ${{ github.repository }} completed successfully!
