name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465

        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}

        subject: Github Actions job result
        to: obiwan@example.com,yoda@example.com

        from: Luke Skywalker # OR 'Luke Skywalker <user@example.com>'

        body: Build job of ${{ github.repository }} completed successfully!
